version: '3.8'


services:

  mariadb:
    image: mariadb
    stdin_open: true
    tty: true
    working_dir: /app
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "1337:80"
    environment:
      PMA_HOST: mariadb
    volumes:
      - .:/app

volumes:
  data: